#!/usr/bin/perl -w

# reads in .hapread file generated by generateReads.pl and outputs number of reads that have a given SNP

my %snppos;

while ( <> ) {
	if ($_ =~ /rid.+pos\:\s(\d+)\,/) {
		$snppos{$1}++;
	}
}
for my $pos (keys %snppos) {
	print "$pos: $snppos{$pos}\n";
}
