#!/usr/bin/perl -w

# reads in .err file generated by 3generateReads.pl and runs redErr.pl on it with a range of pruning thresholds.

use strict;

my $errfile = $ARGV[0];
my $hapfile = $ARGV[1];

my $thres = 1;
my $res;

while ( $thres <= 4 ) {
	print "\n====\nfile: $errfile\nhaps: $hapfile\nThres (SDs away from mean): $thres\n\n";
	$res = `perl redErr.pl -t $thres -r rangenome10k.fa -e $errfile -h $hapfile`;
	print $res;
	$thres += 0.2;
}


